### ISSUE TITLE
 Expose ws_xpixel and ws_ypixel

### ISSUE THREAD

**Issue by swsnr** [eminence/terminal-size#22]
`winsize` also exposes the window size of the terminal in pixels which supports image drawing (e.g. in Kitty).  Would you mind to expose it as well?

**Comment by lunaryorn** [comment]
PS: I'm happy to open a pull request, but I'm not sure how to add this in the current API, given that I can't add any fields to the return value of `terminal_size` :thinking:

**Comment by eminence** [comment]
How about a new method, available only on windows, named `terminal_pixel_size` or something?

**Comment by lunaryorn** [comment]
@eminence I'm sorry, I guess my ticket wasn't exactly precise.

I'm not referring to Windows; I'm referring to the [two extra fields `ws_xpixel` and `ws_pixel` in the POSIX `WinSize` struct](https://github.com/eminence/terminal-size/blob/253a3767f631663e6599fa511d805e71cffcb19a/src/unix.rs#L27).  These fields hold the window size in pixels.

This crate already queries these fields implicitly because it's the same struct and the same ioctl as for the character size, but it doesn't expose these fields in its API.

I'd not like to have a separate function for the window size in pixels since that'd essentially run the ioctl twice if I need both kinds of dimension.   Ideally I'd like to see a function which gets both at once.

That said I don't cling to it; I'm currently calling the ioctl manually in my code to get this information and I'm fine with it, I just thought this might be a good addition to this crate.  If it doesn't fit the API however I'm fine with passing this ticket.

**Comment by eminence** [comment]
Ah, I see now.  I'm sorry for misunderstanding you!

Yes, I agree that making two calls would not be a good idea.  I haven't yet done any research into `ws_xpixel` and `ws_ypixel`, but here are just some quick thoughts:

Does Windows have something similar?  And does MacOS also fill in these two fields?  If so, we could consider a semver version bump and expose all 4 values in the return value for `terminal_size`.

We could also consider a new API function that returns all 4 values, that would be available to anyone who also needs the pixel size in addition to the number of columns and rows.  This might be a path forward if pixel dimensions aren't available on some platforms.

**Comment by lunaryorn** [comment]
> Does Windows have something similar? 

I don't know, and I must admit that I don't care for Windows so much as to feel an urge to find it out :wink: 

>  And does MacOS also fill in these two fields?

It's not the OS, it's the terminal emulator which fills these fields.  

It's a POSIX API, so it exists on macOS just like on Linux, and any terminal that fills this on Linux (e.g. Kitty) will also fill it on macOS.  I presume iTerm2 also fills it, because iTerm2 generally goes a long way to support all kinds of terminal things, but I don't know. 

I don't have access to a macOS system to check.

> If so, we could consider a semver version bump and expose all 4 values in the return value for terminal_size.

You could have an `Option<(Width, Height, Option<(PixelWidth, PixelHeight)>)`, the latter being `None` on Windows until someone makes a pull request to add this if it exists on Windows.

On POSIX (Linux, macOS) we could set these fields if the corresponding `WinSize` fields are not 0.

But I'm also fine with a separate function. I can make a PR either way, I just don't want to make the decision, and I won't do any Windows stuff (I just don't care enough for Windows :innocent: )
