### ISSUE TITLE
Tag 0.3?

### ISSUE THREAD

**Issue by chenx97** [eminence/terminal-size#59]
So that I can use the new features and dependencies rn.

**Comment by eminence** [comment]
v0.3.0 is tagged and also released on crates.io

**Comment by cgwalters** [comment]
Hi, why did this bump semver?  AFAICS there weren't any API incompatible changes?

This crate is "between" some other major crates (like clap) and its main dependency of rustix.  I'd like to avoid multiple copies of rustix in my dependency chain.

Having semver bumps in this crate makes it much more likely that we have multiple rustix copies.

**Comment by cgwalters** [comment]
xref https://github.com/clap-rs/clap/pull/5129

**Comment by eminence** [comment]
Hi, there is a semver bump for two reasons:

* There is a change to MSRV (as part of the update to the latest rustix).  I know that there is not really any community consensus about if MSRV changes deserve semver bumps or not (and many people think that semver bumps are not appropriate), but I personally have been annoyed when a project stops building after a `cargo update` due to a change in MSRV.
* There are no API changes, but the behavior of the `terminal_size()` changed in a possibly subtle way:   It used to only look at STDOUT, but now it looks at all three streams (STDOUT, STDERR, STDIN).   For example, if your command had stdout redirected to a file, `terminal_size()` used to return nothing, and now it returns a size.

I realize that both of these reasons are each pretty weak reasons to bump from v0.2 to 0.3, and so if you disagree with the version bump, I can definitely understand why.

**Comment by cgwalters** [comment]
OK thanks, that is fair.  For the first one, I'm personally in the camp that msrv bumps are not semver bumps, particularly because as of nowadays you can set `rust-version` in your Cargo.toml and this is the appropriate way to set MSRV!  There's been discussions that in the future cargo may become msrv-aware and fix that exact problem.

> but the behavior of the terminal_size() changed in a possibly subtle way: I

Fair enough, this is perhaps on the line for a semver bump IMO, but I understand it.

Overall, a great thing about Rust is indeed the design of semver and being able to evolve library crates.  I just feel we need to be mindful of the cost-benefit of doing so, as it necessarily implies work for downstream crate maintainers.

**Comment by eminence** [comment]
Yeah, fully understood.  In some cases, it's a balancing act:  Don't update semver and risk breaking downstream crates (requiring them to manually pin some dependencies), or update semver and force downstream crates to updates dependencies to reduce duplications in the crate graph.

I am very eagerly awaiting the day when cargo becomes MSRV-aware :)

**Comment by epage** [comment]
> in the future cargo may become msrv-aware and fix that exact problem.

`cargo +nightly update -Zmsrv-policy` uses an MSRV-aware resolver.  Its far from ideal and there is a long road to stabilization, but it helps.

**Comment by eminence** [comment]
I didn't realize cargo had an initial implementation of this.  Very cool!

**Comment by epage** [comment]
As of [3 weeks ago](https://github.com/rust-lang/cargo/pull/12560).  See [the tracking issue](https://github.com/rust-lang/cargo/issues/9930) for where it falls short.

**Comment by cgwalters** [comment]
So then https://github.com/eminence/terminal-size/pull/60

**Comment by chenx97** [comment]
FYI, the subtle API change mentioned [here](https://github.com/eminence/terminal-size/pull/57#issuecomment-1702111389) made me ask for 0.3 here instead of 0.2.7.
