### ISSUE TITLE
[Question] Why a newtype instead of a type alias?

### ISSUE THREAD

**Issue by alexmozaidze** [eminence/terminal-size#65]
Why are Width and Height their own structs? Why not just alias it like
```rust
type Width = int;
type Height = int;
```
If it's really that necessary to keep it as structs, then why aren't these structs `#[repr(transparent)]`?

**Comment by eminence** [comment]
As a personal preference, I don't like functions that return things like `(u16, u16)` because you don't know if it returns (width, height) or (height, width) without checking the docs.  So the newtypes are supposed to help with this.

> why aren't these structs `#[repr(transparent)]`?

Because `#[repr(transparent)]` didn't exist when I first wrote this code :)
